all: Problem04
	g++ -L. Problem04.o -o Problem04

Problem04: problem04.cpp
	g++ -std=c++11 -c problem04.cpp -o Problem04.o

clean:
	rm *.o -f
	rm Problem04 -f
	
reset:
	rm *.o -f
	rm Problem04  -f
	rm *_sol*